// Filter Quizzes
export const SET_TEXT_FILTER = "SET_TEXT_FILTER";
export const SORT_BY_DIFFICULTY = "SORT_BY_DIFFICULTY";

// Fetch Quizzes
export const FETCH_QUIZES_STARTED = "FETCH_QUIZES_STARTED";
export const FETCH_QUIZES_SUCCEEDED = "FETCH_QUIZES_SUCCEEDED";
export const FETCH_QUIZES_FAILED = "FETCH_QUIZES_FAILED";

// Quiz Operations
export const ADD_QUIZ_SUCCEEDED = "ADD_QUIZ_SUCCEEDED";
export const ADD_QUIZ_FAILED = "ADD_QUIZ_FAILED";
export const REMOVE_QUIZ_SUCCEEDED = "REMOVE_QUIZ_SUCCEEDED";
export const REMOVE_QUIZ_FAILED = "REMOVE_QUIZ_FAILED";
export const EDIT_QUIZ_SUCCEEDED = "EDIT_QUIZ_SUCCEEDED";
export const EDIT_QUIZ_FAILED = "EDIT_QUIZ_FAILED";

// Auth Signup
export const SIGN_UP_CONFIRMED = "SIGN_UP_CONFIRMED";
export const SIGN_UP_FAILED = "SIGN_UP_FAILED";

// Auth Login
export const LOG_IN_CONFIRMED = "LOG_IN_CONFIRMED";
export const LOG_IN_FAILED = "LOG_IN_FAILED";
export const LOG_OUT_ACTION = "LOG_OUT_ACTION";

// Admin Permissons
export const FETCH_ALL_USERS_STARTED = "FETCH_ALL_USERS_STARTED";
export const FETCH_ALL_USERS = "FETCH_ALL_USERS";
export const FETCH_ALL_USERS_FAILED = "FETCH_ALL_USERS";
export const DELETE_ALL_USERS = "DELETE_ALL_USERS";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

// Update the User
export const UPDATE_USER = "UPDATE_USER";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_DATA_FAILED = "SET_USER_DATA_FAILED";
export const REMOVE_USER_DATA = "REMOVE_USER_DATA";
export const FETCH_USER_PROFILE = "FETCH_USER_PROFILE";

// Play the Quiz
export const PLAY_QUIZ_STARTED = "PLAY_QUIZ_STARTED";
export const PLAY_QUIZ_SUCCEEDED = "PLAY_QUIZ_SUCCEEDED";
export const PLAY_QUIZ_FAILED = "PLAY_QUIZ_FAILED";

// Add Coins to User Account
export const ADD_COINS_TO_USER_SUCCEEDED = "ADD_COINS_TO_USER_SUCCEEDED";
export const ADD_COINS_TO_USER_FAILED = "ADD_COINS_TO_USER_FAILED";

// Theme Controller Actions
export const SET_LIGHT_MODE = "SET_LIGHT_MODE";
export const SET_DARK_MODE = "SET_DARK_MODE";

// USER PROFIL
export const USER_PROFIL_REQUEST = "USER_PROFIL_REQUEST";
export const USER_PROFIL_FAILED = "USER_PROFIL_FAILED";
export const USER_PROFIL_SUCCESS = "USER_PROFIL_SUCCESS";

// Update (Edit a Profile User)
export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

// Forgot and Reset password
export const USER_FORGOT_REQUEST = "USER_FORGOT_REQUEST";
export const USER_FORGOT_SUCESS = "USER_FORGOT_SUCESS";
export const USER_FORGOT_FAIL = "USER_FORGOT_FAIL";

export const USER_RESET_PASSWORD_REQUEST = "USER_RESET_PASSWORD_REQUEST";
export const USER_RESET_PASSWORD_SUCESS = "USER_RESET_PASSWORD_SUCESS";
export const USER_RESET_PASSWORD_FAIL = "USER_RESET_PASSWORD_FAIL";

// Update profil user
export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_FAIL";
export const UPDATE_PASSWORD_REQUEST = "UPDATE_PROFILE_FAIL";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PROFILE_FAIL";
export const UPDATE_PASSWORD_RESET = "UPDATE_PROFILE_FAIL";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PROFILE_FAIL";

export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";

// lOARD uSER
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
// Clear Errors
export const CLEAR_ERROR = "CLEAR_ERROR";
